-- DROP DATABASE IF EXISTS bitsdb;
CREATE DATABASE bitsdb;
USE bitsdb;

-- DROP TABLE Users;

CREATE TABLE Users (
user_id INT AUTO_INCREMENT PRIMARY KEY,
userName VARCHAR(200),
photo VARCHAR(200),
email VARCHAR(200),
password VARCHAR(200),
comedian INTEGER,
createdAt VARCHAR(200),
updatedAt VARCHAR(200)
);